I can promise 30 minutes per appointment, longer if needed depending on the issues.
I am not your personal tutor, so please try attending assigned office hours, asking questions first on our [campuswire](https://campuswire.com), and collaborating with classmates. If you are still struggling or can't resolve the issues you are having,
feel free to set up an appointment with me. 


## Appropriate Email

Hello Jose,

*(Reason for wanting to meet outside office hours)*

My available times this week are

- Monday: ANYTIME
- Tueday: 10am-12pm, 2-3pm
- Wednesday: 10am-1pm
- Thursday: ANYTIME
- Friday, 8am-2pm

Do any of these times work for you?

*your signature*



## Not Appropriate Email

Hello Jose,

Can we setup an appointment? Im struggling with the assignment 


In the *not appropriate email* example, I reply yes then give you my available times, afterwards you reply you can't meet during those times so you send me your available times, and then I proceed to agree with those times etc...
This long and tedious process can be avoid from the start if you just follow the first example :)

