---
comments: false
---

## Current Courses

-   CSUF Math 120: Elementary Statistics *(Fall 2024)*

-   CSUF Math 338: [Statistics Applied to Natural Science](https://csuf-math338.netlify.app) *(Fall 2024)*

## Previous Courses

### University of California, Los Angeles

+--------------------+------------------------------------------------------------------------------------+---------------------------------------+
| Course Number      | Course Name                                                                        | Terms                                 |
+====================+====================================================================================+=======================================+
| STATS 10           | Introduction to Statistical Reasoning                                              | *Fall 2022, Winter 2023, Spring 2023* |
+--------------------+------------------------------------------------------------------------------------+---------------------------------------+
| STATS 13           | [Introduction to Statistical Methods for Life](https://ucla-stats13.netlify.app)[\ | *Summer 2022, Fall 2023*              |
|                    | ](#0)[and Health Sciences](https://ucla-stats13.netlify.app)                       |                                       |
+--------------------+------------------------------------------------------------------------------------+---------------------------------------+
| STATS 20           | Introduction to Statistical Programming with R                                     | *Summer 2024*                         |
+--------------------+------------------------------------------------------------------------------------+---------------------------------------+
| STATS 21           | Python and Other Technologies for Data Science                                     | *Spring 2023*                         |
+--------------------+------------------------------------------------------------------------------------+---------------------------------------+
| STATS 100B         | Introduction to Mathematical Statistics                                            | *Summer 2023*                         |
+--------------------+------------------------------------------------------------------------------------+---------------------------------------+
| STATS 100C         | Linear Models                                                                      | *Summer 2023*                         |
+--------------------+------------------------------------------------------------------------------------+---------------------------------------+
| STATS 140XP/ 141XP | Practice of Statistical Consulting                                                 | *Winter 2024,* *Spring 2024*          |
+--------------------+------------------------------------------------------------------------------------+---------------------------------------+

### California State University, Fullerton

+---------------+---------------------------------------+--------------------------+
| Course Number | Course Name                           | Terms                    |
+===============+=======================================+==========================+
| Math 115      | College Algebra                       | *Fall 2019*              |
+---------------+---------------------------------------+--------------------------+
| Math 120      | Elementary Statistics                 | *Spring 2020, Fall 2020* |
+---------------+---------------------------------------+--------------------------+
| Math 338      | Statistics Applied to Natural Science | *Spring 2021*            |
+---------------+---------------------------------------+--------------------------+
