---
title: "Welcome To STATS10"
---

## Introduction to Statistical Reasoning

:::callout-important
## Useful Links


- [Zoom](https://ucla.zoom.us/j/4285433918?pwd=TVpIRndYYmZSeTg0NUUvYlhTWllUQT09)
For online discussion and/or virtual office hours
- [Box Folder](https://app.box.com/s/3pfoq99zhvyyi99wdc1kzoojsihgcoxu) All material for the labs will be posted here
- [campuswire](https://campuswire.com) Have discussions or ask questions regarding this course
- [Lecture Recordings](/zoom.qmd) Recordings of lectures and other tutorials
:::

**Discussions:** <br/>
**4A** M/W: 12:00pm-12:50pm (Online)
 <br/>
**4B** M/W: 1:00pm-1:50pm (PAB 1749)

**Office Hours:** <br/>
M/W: 12:00pm-12:50pm <br/>
@MS8349 or
[Zoom](https://ucla.zoom.us/j/4285433918?pwd=TVpIRndYYmZSeTg0NUUvYlhTWllUQT09) <br/>
or by [appointment](/email.qmd)

**Email**: toledo60@g.ucla.edu

Material from this course can be downloaded from this [Box Folder](https://app.box.com/s/3pfoq99zhvyyi99wdc1kzoojsihgcoxu)

For general questions or specific questions about the labs use [campuswire](https://campuswire.com). Otherwise, you can email me personally. The class code to join campuswire is posted on CANVAS

All lab assignments will be turned in directly on CANVAS

Below are all the labs regrading this course. 
In labs, you will apply the concepts discussed in lectures but with a focus on computation. All labs will be completed using R and documented with R markdown.


::: callout-warning
Lab tutorials are a work in progress and are constantly being updated
:::

- [Lab 1: Introduction to R](/ucla/stats10/lab1.qmd)
- [Lab 2: Logical Statements with Applications](/ucla/stats10/lab2.qmd)
- [Lab 3: Introduction to Linear Regression and Sampling](/ucla/stats10/lab3.qmd)


