{
  "hash": "455ad1b06b8272c4f7c488393e680a02",
  "result": {
    "markdown": "---\ntoc: true\n---\n\n\n\n\n## Overview of Confidence Intervals for a Proportion\n\n\nA point estimate is a single quantity estimating the population parameter. It would be more ideal to give a range of plausible values for the parameter instead with some given *confidence*.\n\nRecall a *point estimate* for the population proportion is the sample proportion $\\hat{p}$:\n$$\n\\hat{p} \\rightarrow p\n$$\nAn *interval estimate* for the population proportion will then be of the form:\n$$\n(LB,UB) \\rightarrow p\n$$\n\nwhere the lower bound is \n\n*LB = point estimate - margin of error* \n\nSimilarly, the upper bound is \n\n*UB = point estimate + margin of error*\n\nA margin of error consists of the standard error and a critical value determined by the confidence level.\nThe margin of error can be defined as \n\n*Margin of Error = Critical Value x Standard Error*\n\nThe critical value that we use may be obtained from a $t$-distribution if the assumptions necessary for the Central Limit Theorem *(CLT)* are not valid. Alternatively, if these assumptions hold, we can obtain the critical value from a standard normal distribution.\n\n\nTo verify the assumptions to apply CLT, we must have at least 10 successes and 10 failures\n$$\nn \\hat{p} \\geq 10 \\quad \\& \\quad n(1-\\hat{p}) \\geq 10\n$$\nGiven the assumption hold, the margin of error can be calculated as \n$$\nME = z^* \\times SE\n$$\nwhere $z^*$ is a value obtained from a standard normal distribution given a certain confidence level.\nTypical confidence levels include $90\\%,95\\%,99\\%$, We can visualize how to obtain the critical values $z^*$ for these values as follows\n\n<details>\n<summary>Show Code</summary>\n\nThis code is for teaching purposes only, you do not need them for your lab\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(patchwork)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_set(theme_bw())\ntheme_replace(panel.grid.minor = element_blank(),\n              panel.grid.major = element_blank())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nx_limits <- c(-4,4)\n\np1 <- ggplot(data.frame(x = x_limits), aes(x)) +\n  stat_function(fun = dnorm,\n                geom = \"line\",\n                xlim = x_limits) +\n  stat_function(fun = dnorm,\n                geom = \"area\",\n                fill = 'steelblue',\n                alpha =0.3,\n                xlim = c(-1.65, 1.65))+\n  geom_vline(xintercept = 1.65,linetype=2,color = 'steelblue')+\n  geom_vline(xintercept = -1.65,linetype=2,color = 'steelblue')+\n  labs(x = '',y= 'Density')+\n  annotate(\"text\", x = 0, y = 0.1, \n           label = paste0(90,\"%\"),\n           size=4.5)+\n  scale_x_continuous(name = '',limits = x_limits,\n                     breaks = -4:4)\n\np2 <- ggplot(data.frame(x = x_limits), aes(x)) +\n  stat_function(fun = dnorm,\n                geom = \"line\",\n                xlim = x_limits) +\n  stat_function(fun = dnorm,\n                geom = \"area\",\n                fill = '#cf5d55',\n                alpha =0.3,\n                xlim = c(-1.96, 1.96))+\n  geom_vline(xintercept = 1.96,linetype=2,color = '#cf5d55')+\n  geom_vline(xintercept = -1.96,linetype=2,color = '#cf5d55')+\n  labs(x = '',y= 'Density')+\n  annotate(\"text\", x = 0, y = 0.1, \n           label = paste0(95,\"%\"),\n           size=4.5)+\n  scale_x_continuous(name = '',limits = x_limits,\n                     breaks = -4:4)\n\np3 <- ggplot(data.frame(x = x_limits), aes(x)) +\n  stat_function(fun = dnorm,\n                geom = \"line\",\n                xlim = x_limits) +\n  stat_function(fun = dnorm,\n                geom = \"area\",\n                fill = '#71c7b0',\n                alpha =0.3,\n                xlim = c(-2.58, 2.58))+\n  geom_vline(xintercept = -2.58,linetype=2,color = '#71c7b0')+\n  geom_vline(xintercept = 2.58,linetype=2,color = '#71c7b0')+\n  labs(x = '',y= 'Density')+\n  annotate(\"text\", x = 0, y = 0.1, \n           label = paste0(99,\"%\"),\n           size=4.5)+\n  scale_x_continuous(name = '',limits = x_limits,\n                     breaks = -4:4)\n```\n:::\n\n\n</details>\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](confidence_intervals_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n\n* For a 90\\% CI use $z^* = 1.65$\n* For a 95\\% CI use $z^* = 1.96$\n* For a 99\\% CI use $z^* = 2.58$\n\nIn general, for a $100 \\times (1-\\alpha)\\%$ CI the correspond critical value will be $z_{1-\\alpha/2}^*$ which can then easily be computed using `qnorm`. For example, if for some reason we were interested in a \n$78\\%$ CI = $100 \\times (1-0.22)$ the corresponding critical value would be $z_{1-0.22/2}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(1-0.22/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1.226528\n```\n:::\n:::\n\n\nWe can verify this with the usual confidence interval levels:\n\nFor a 90\\% CI use $z^* = 1.65$\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(1-0.1/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1.644854\n```\n:::\n:::\n\n\nFor a 95\\% CI use $z^* = 1.96$\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(1-0.05/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1.959964\n```\n:::\n:::\n\n\nFor a 99\\% CI use $z^* = 2.58$\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(1-0.01/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 2.575829\n```\n:::\n:::\n\n\n\nNow that we know how to obtain the critical value, all that is left to do is compute the standard error. The standard error is \n$$\nSE(\\hat{p}) = \\sqrt{\\frac{p(1-p)}{n}}\n$$\nTherefore, a $100(1-\\alpha)\\%$ CI becomes\n$$\n\\begin{align*}\n100(1-\\alpha)\\% \\, CI &=  \n(LB,UB) \\\\[5pt]\n&= (\\hat{p} - ME, \\hat{p}+ME) \\\\[5pt]\n&= (\\hat{p} - z_{1-\\alpha/2} \\times SE, \\, \\, \\hat{p} + z_{1-\\alpha/2} \\times SE ) \\\\[5pt]\n&= \\left(\\hat{p} - z_{1-\\alpha/2}^* \\, \\sqrt{\\frac{p(1-p)}{n}}, \\,\\,\n\\hat{p} + z_{1-\\alpha/2}^* \\, \\, \\sqrt{\\frac{p(1-p)}{n}} \\right)\n\\end{align*}\n$$\n\n**Interpretation**\n\n> If repeated samples were taken and the $95\\%$ confidence interval computed for each sample, $95\\%$ of the intervals would contain the population parameter. Naturally, $5\\%$ of the intervals would not contain the population parameter\n\n\n**Procedure**\n\n1. Identify the population of interest and corresponding parameter\n2. Obtain a suitable sample and an initial point estimate\n3. Check validity assumptions to apply CLT\n4. Calculate margin of error\n5. Obtain lower and upper bounds\n6. Interpret your $100(1-\\alpha)\\%$ interval estimate in the context of the problem\n\nWe will use the `pawnee` dataset in our class website to illustrate this procedure.\n\n## Dataset Description\n\nA brief description of the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\npawnee <- read.csv(file=\"/Users/toledo60/Desktop/Projects/personal-website/ucla/stats10/data/pawnee.csv\")\n```\n:::\n\n\n\n> The Sweetums candy factory in Pawnee, Indiana, is under investigation for violating EPA regulations. Factory workers have improperly disposed of arsenic and sulfur waste from the candy-making process, and the contamination has reached the local water supply! We have data for arsenic and sulfur levels from the water in all houses within a 2-mile radius of the factory\n\n\nSome important variables include:\n\n* `Arsenic`: arsenic levels for each home in ppm\n* `Sulfur`: sulfur levels for each home in ppm\n* `New_hlth_issue`: Indicates `Y` is someone living at the home has experienced a major health issue after the date of contamination, `N` if no new health complications\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(pawnee)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>   ID Latitude Longitude Arsenic Sulfur New_hlth_issue\n#> 1  1 41.09414 -85.60974       0      0              N\n#> 2  2 41.09054 -85.70344       0    130              N\n#> 3  3 41.08601 -85.71996       4    170              N\n#> 4  4 41.08100 -85.75415       0      0              Y\n#> 5  5 41.07435 -85.70043       0      0              N\n#> 6  6 41.07399 -85.71788       0      0              N\n```\n:::\n:::\n\n\n\nWe will construct a confidence interval for the population proportion of of households experiencing a major health issue caused by the EPA violations of the Sweetums candy factory in Pawnee, Indiana.\n\n\n## Constructing a confidence interval\n\n\n**Identify the population of interest and corresponding parameter**\n\nOur population of interest is all houses within a 2-mile radius of Sweetums candy factory in Pawnee, Indiana.\nThe parameter is the proportion of houses within a 2-mile radius of Sweetums candy factory in Pawnee, Indiana which experienced a major health issue after the date of contamination\n\n**Obtain a suitable sample and an initial point estimate**\n\nOur sample will consist of 30 randomly chosen households from the `pawnee` dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1337)\nrows_to_sample <- sample(1:nrow(pawnee), size = 30)\npawnee_sample <- pawnee[rows_to_sample,]\nn <- nrow(pawnee_sample)\n```\n:::\n\n\nThe initial point estimate, i.e the sample proportion of houses within a 2-mile radius of Sweetums candy factory in Pawnee, Indiana which experienced a major health issue after the date of contamination \n\n\n::: {.cell}\n\n```{.r .cell-code}\np_hat <- mean(pawnee_sample$New_hlth_issue==\"Y\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.2\n```\n:::\n:::\n\n\n\n**Check validity assumptions to apply CLT**\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_hat * n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 6\n```\n:::\n\n```{.r .cell-code}\n(1-p_hat) * n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 24\n```\n:::\n:::\n\n\nThere were at least 10 failures but not at least 10 successes. However, we have a sufficiently large enough sample size $n \\geq 30$ to apply the CLT. Therefore, the sampling distribution of the sample proportion is approximately normal\n\n$$\n\\hat{p} \\sim N \\left(p, \\sqrt{\\frac{p(1-p)}{n}} \\right)\n$$\n\n**Calculate margin of error**\n\nThe margin of error is defined as \n\n$$\nME = z_{1-\\alpha/2} \\times SE(\\hat{p})\n$$\nWe are interested in a 95\\% confidence interval for the population proportion \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\ncritical_value <- qnorm(1-alpha/2)\nSE <- sqrt(p_hat * (1-p_hat)/n)\n```\n:::\n\n\nPutting all of this together, we can compute the margin error \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmargin_error <- critical_value * SE\nmargin_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.1431355\n```\n:::\n:::\n\n\n\n**Obtain lower and upper bounds**\n\nThe lower bound is *LB = point estimate - margin of error*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlb = p_hat - margin_error\n```\n:::\n\n\nThe upper bound is *UB = point estimate + margin of error*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nub = p_hat + margin_error\n```\n:::\n\n\n\nTherefore, our 95\\% CI is \n\n::: {.cell}\n\n```{.r .cell-code}\nc(lb,ub)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.05686447 0.34313553\n```\n:::\n:::\n\n\n\n**Interpret your $100(1-\\alpha)\\%$ interval estimate in the context of the problem**\n\nWe are 95\\% confident the true population proportion of households within a 2-mile radius of Sweetums candy factory in Pawnee, Indiana which experienced a major health issue after the date of contamination is between 5.69\\% and 34.31\\%\n\n\nTaking a look at the true population proportion \n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- mean(pawnee$New_hlth_issue == 'Y')\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.2920518\n```\n:::\n:::\n\n\nwe see that our constructed confidence interval does contain the true population proportion\n\n\n::: {.cell}\n\n```{.r .cell-code}\np >= lb && p <= ub\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] TRUE\n```\n:::\n:::\n",
    "supporting": [
      "confidence_intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}