---
author: Jose Toledo Luna
date: 2023-05-03
title: Participation Project
description: Participation project for stats21 discussions
toc: true
comments: false
---


The goal of this project is for you to create a simple exploratory data analysis application (EDA). You will do so using the [streamlit](https://streamlit.io) framework


## Streamlit Application Structure

- Have a [file uploader button ](https://docs.streamlit.io/library/api-reference/widgets/st.file_uploader) which allows you to upload your own `csv` file
- Once the `csv` file has been uploaded display relevant statistics about the dataset, such as: number of rows, number of columns, how many categorical/numerical/bool variables are there *(other information you can think of, optional)*

- An appropriate [input widget](https://docs.streamlit.io/library/api-reference/widgets) to select a **single** column from the dataset. *(If you are a looking for a challenge select multiple columns, optional)*

- Once the chosen column has been selected, if the column is numerical display in a table the [five number summary](https://en.wikipedia.org/wiki/Five-number_summary), create a distribution plot using matplotlib/seaborn. The plot should be highly customized, I recommend [The Python Graph Gallery](https://www.python-graph-gallery.com) for examples and inspiration 

- If the column selected is categorical, display in a table the proportions of each category level, and create a customized barplot

I leave the customization of your streamlit application up to you. For example, the layout, theme, single or multiple pages, etc..


## Github Repository Structure

In order for streamlit to host your application properly *(and free)* you need to have a **public** repository with the contents of your application.

The structure be something like this:

- Include a `README.md` file that provides a brief summary of your application and includes any pertinent details or instructions

- a `.gitignore` specifying files for git to not keep track of,
see [Introduction to Streamlit](/ucla/stats21/discussions/02-streamlit.qmd) and 
[Github Overview](/ucla/stats21/discussions/03-git.qmd)  for additional reference

- a `requirements.txt` file specifying all of the packages used for your streamlit application. I recommend using a [virtual environment](/ucla/stats21/discussions/04-virtualenv.qmd)




















